### ISSUE TITLE
English color values fail on iOS

### ISSUE THREAD

**Issue by deobald** [pariyatti/mobile-app#52]
It would appear these are not valid on iOS ... or perhaps Flutter stopped understanding them in the past 6 months.

![pariyatti-ios-exception](https://user-images.githubusercontent.com/20282/107137972-ef2e2180-68d6-11eb-9b2f-7eccd55f6cb8.jpg)

```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following FormatException was thrown building OverlayInspirationCard(dirty):
flutter: Invalid radix-10 number (at character 1)
flutter: white
flutter: ^
flutter:
flutter: The relevant error-causing widget was:
flutter:   OverlayInspirationCard
flutter:   file:///Users/steven/work/pariyatti/mobile-app/lib/ui/screens/today/TodayScreen.dart:52:18
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      int._throwFormatException (dart:core-patch/integers_patch.dart:131:5)
flutter: #1      int._parseRadix (dart:core-patch/integers_patch.dart:142:16)
flutter: #2      int._parse (dart:core-patch/integers_patch.dart:100:12)
flutter: #3      int.parse (dart:core-patch/integers_patch.dart:63:12)
flutter: #4      OverlayInspirationCard.build (package:patta/ui/common_widgets/cards/OverlayInspirationCard.dart:136:50)
< the rest of the stack trace is elided >
```

**Comment by NamanShergill** [comment]
Fixed in https://github.com/pariyatti/mobile-app/pull/53
